allprojects {
    group = 'org.brassbrewery'
    version = '0.1'

    repositories {
        mavenCentral()
        maven {
            name = "papermc-repo"
            url = "https://repo.papermc.io/repository/maven-public/"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/groups/public/"
        }
        maven {
            name = 'mcmmo-repo'
            url = "https://nexus.neetgames.com/repository/maven-public"
        }
        maven {
            name = 'glaremasters repo'
            url = 'https://repo.glaremasters.me/repository/towny/'
        }
        maven {
            url = "https://maven.enginehub.org/repo/"
        }
        maven {
            url 'https://repo.codemc.org/repository/maven-public'
        }

    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(21))
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release.set(21)
    }
    dependencies {
        compileOnly("io.papermc.paper:paper-api:1.21.5-R0.1-SNAPSHOT")
    }
}
