package org.brassbrewery.fragaliciousLib.combat.config;

import org.brassbrewery.fragaliciousLib.configs.FragaliciousConfig;
import org.brassbrewery.fragaliciousLib.configs.objects.IntegerConfigObject;
import org.brassbrewery.fragaliciousLib.structure.FragaliciousPlugin;

import java.nio.file.Path;

public class CombatMainConfig extends FragaliciousConfig {
    public IntegerConfigObject combatTimer;
    public CombatMainConfig(FragaliciousPlugin plugin) {
        super(plugin, "Combat") ;
    }

    @Override
    public void registerAllConfigObjects() {
        combatTimer = new IntegerConfigObject("combat.timer", 30, "Time in seconds before a player not hit is no longer considered to be in combat");
        registerConfigObject(combatTimer);
    }


    // <AUTO-GENERATED-GETTERS-START>
    public Integer getCombatTimer() {
        return this.combatTimer.getValue();
    }
    // <AUTO-GENERATED-GETTERS-END>
}
