plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"
}

dependencies {
    testImplementation 'org.mockbukkit.mockbukkit:mockbukkit-v1.21:4.72.2'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation project(":fragalicious-core")
    implementation 'com.palmergames.bukkit.towny:towny:0.101.1.0'
    implementation "com.gmail.nossr50.mcMMO:mcMMO:2.2.004"
}
tasks {
    runServer {
        minecraftVersion("1.21")
    }
}
test {
    useJUnitPlatform()
}
java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

