package org.brassbrewery.fragaliciousCore.anomaly.config;

import org.brassbrewery.fragaliciousCore.FragaliciousCore;
import org.brassbrewery.fragaliciousCore.configs.FragaliciousConfig;

public class AnomalySettingsConfig extends FragaliciousConfig {
    public AnomalySettingsConfig() {
        super(FragaliciousCore.getInstance(), "anomaly-settings");
    }

    @Override
    public void registerAllConfigObjects() {

    }


        // <AUTO-GENERATED-GETTERS-START>

// <AUTO-GENERATED-GETTERS-END>
}
