package org.brassbrewery.fragaliciousLib.anomaly.config;

import org.brassbrewery.fragaliciousLib.FragaliciousLib;
import org.brassbrewery.fragaliciousLib.configs.FragaliciousConfig;
import org.brassbrewery.fragaliciousLib.configs.objects.BooleanConfigObject;
import org.brassbrewery.fragaliciousLib.configs.objects.IntegerConfigObject;
import org.brassbrewery.fragaliciousLib.configs.objects.StringConfigObject;
import org.bukkit.plugin.Plugin;

public abstract class AnomalyConfig extends FragaliciousConfig {
    private String id;
    private BooleanConfigObject isEnabled;
    //generic
    private IntegerConfigObject weight;
    private BooleanConfigObject isJoinable;
    //ingame info
    private StringConfigObject name;
    private StringConfigObject description;
    //discord
    private BooleanConfigObject sendEmbed;
    private StringConfigObject discordDescription;
    private StringConfigObject discordTitle;
    private IntegerConfigObject color;

    /**
     * Creates a new anomaly configuration file.
     * Requires passing the owning plugin and an Anomaly Configuration Object.
     *
     * @param plugin
     * @param anomalyConfigObject - The anomaly's default configuration object.
     */
    public AnomalyConfig(Plugin plugin, AnomalyConfigObject anomalyConfigObject) {
        super(FragaliciousLib.getInstance(), plugin.getName() + "_" +anomalyConfigObject.getDefaultName());
        id = plugin.getName() + "_" +anomalyConfigObject.getDefaultName();
        isEnabled = anomalyConfigObject.getIsEnabled();
        weight = anomalyConfigObject.getWeight();
        isJoinable = anomalyConfigObject.getIsJoinable();
        name = anomalyConfigObject.getName();
        description = anomalyConfigObject.getDescription();
        sendEmbed = anomalyConfigObject.getSendEmbed();
        discordDescription = anomalyConfigObject.getDiscordDescription();
        discordTitle = anomalyConfigObject.getDiscordTitle();
        color = anomalyConfigObject.getColor();
    }

    /**
     * Registers all anomaly configuration objects.
     */
    @Override
    public void registerAllConfigObjects() {
        registerConfigObject(isEnabled);
        registerConfigObject(weight);
        registerConfigObject(isJoinable);
        registerConfigObject(name);
        registerConfigObject(description);
        registerConfigObject(sendEmbed);
        registerConfigObject(discordDescription);
        registerConfigObject(discordTitle);
        registerConfigObject(color);
        registerAdditionalConfigObjects();
    }

    /**
     * Registers additional configuration objects for this anomaly.
     * This is meant for additional config settings you may want to add to the default config file.
     * Please remeber to use the GenerateFragaliciousGetters tool in your code
     */
    public abstract void registerAdditionalConfigObjects();

    public String getId() {
        return id;
    }


        // <AUTO-GENERATED-GETTERS-START>
public Boolean getIsEnabled() {
    return this.isEnabled.getValue();
}

public Integer getWeight() {
    return this.weight.getValue();
}

public Boolean getIsJoinable() {
    return this.isJoinable.getValue();
}

public String getName() {
    return this.name.getValue();
}

public String getDescription() {
    return this.description.getValue();
}

public Boolean getSendEmbed() {
    return this.sendEmbed.getValue();
}

public String getDiscordDescription() {
    return this.discordDescription.getValue();
}

public String getDiscordTitle() {
    return this.discordTitle.getValue();
}

public Integer getColor() {
    return this.color.getValue();
}
// <AUTO-GENERATED-GETTERS-END>
}
