package org.brassbrewery.fragaliciousLib.anomaly.config;

import org.brassbrewery.fragaliciousLib.FragaliciousLib;
import org.brassbrewery.fragaliciousLib.configs.FragaliciousConfig;

public class AnomalySettingsConfig extends FragaliciousConfig {
    public AnomalySettingsConfig() {
        super(FragaliciousLib.getInstance(), "anomaly-settings");
    }

    @Override
    public void registerAllConfigObjects() {

    }


        // <AUTO-GENERATED-GETTERS-START>
    
    // <AUTO-GENERATED-GETTERS-END>
}
