package org.brassbrewery.fragaliciousCore.afk;

import org.brassbrewery.fragaliciousCore.FragaliciousCore;
import org.brassbrewery.fragaliciousCore.configs.FragaliciousConfig;
import org.brassbrewery.fragaliciousCore.configs.objects.BooleanConfigObject;
import org.brassbrewery.fragaliciousCore.configs.objects.IntegerConfigObject;
import org.brassbrewery.fragaliciousCore.configs.objects.StringConfigObject;

public class AfkConfig extends FragaliciousConfig {
    //generic
    private IntegerConfigObject afkTimeInSeconds;
    //messages
    private BooleanConfigObject enableAfkMessage;
    private StringConfigObject afkMessageStart;
    private StringConfigObject afkMessageEnd;
    private BooleanConfigObject enableAfkBroadcast;
    private StringConfigObject afkBroadcastStart;
    private StringConfigObject afkBroadcastEnd;

    public AfkConfig(FragaliciousCore plugin ) {
        super(plugin, "AfkModule");
    }

    @Override
    public void registerAllConfigObjects() {
        // Generic
        afkTimeInSeconds = new IntegerConfigObject("afk.generic.kicktime", 300, "How long it takes to go afk in seconds (Default 300)");
        // messages
        enableAfkMessage = new BooleanConfigObject("afk.messages.self.enable", true, "Should we send a message to the player when they go afk?");
        afkMessageStart = new StringConfigObject("afk.messages.self.start",
                "&r&8[&cAFK&8] &7You are now &o&cAFK&r", "Sent to player when they go AFK");
        afkMessageEnd = new StringConfigObject("afk.messages.self.end",
                "&r&8[&aBACK&8] &7You are &a&oNO LONGER AFK&r", "Sent to player when they return from AFK");
        enableAfkBroadcast = new BooleanConfigObject("afk.messages.broadcast.enable", true, "Should we broadcast AFK status changes to others?");
        afkBroadcastStart = new StringConfigObject("afk.messages.broadcast.start",
                "&7* &f{name} &7is now &oAFK", "Broadcast when a player goes AFK");
        afkBroadcastEnd = new StringConfigObject("afk.messages.broadcast.end",
                "&7* &f{name} &7is no longer AFK", "Broadcast when a player comes back from AFK");

        //generic
        super.registerConfigObject(afkTimeInSeconds);
        //messages
        super.registerConfigObject(enableAfkMessage);
        super.registerConfigObject(afkMessageStart);
        super.registerConfigObject(afkMessageEnd);
        super.registerConfigObject(enableAfkBroadcast);
        super.registerConfigObject(afkBroadcastStart);
        super.registerConfigObject(afkBroadcastEnd);
    }

    public Integer getAfkTimeInSeconds() {
        return null;
    }
    // <AUTO-GENERATED-GETTERS-START>

}
