package org.brassbrewery.fragaliciousCore.configs;

import org.brassbrewery.fragaliciousCore.configs.objects.ConfigObject;

import java.io.*;
import java.lang.reflect.Field;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.nio.file.*;
import java.util.*;
import java.util.regex.Pattern;

public class GenerateFragaliciousGetters {

    private static final String PROJECT_ROOT = System.getProperty("user.dir");
    private static final String SRC_DIR = PROJECT_ROOT + "/src/main/java";
    private static final String START_MARKER = "// <AUTO-GENERATED-GETTERS-START>";
    private static final String END_MARKER = "// <AUTO-GENERATED-GETTERS-END>";

    public static void main(String[] args) throws Exception {
        List<Class<?>> configClasses = findAllConfigSubclasses();

        for (Class<?> configClass : configClasses) {
            Path sourceFilePath = findSourceFilePath(configClass);
            if (sourceFilePath == null) continue;

            String originalSource = Files.readString(sourceFilePath);
            String generatedGetters = generateGettersForClass(configClass).trim();

            String autoGeneratedBlock = START_MARKER + "\n" + generatedGetters + "\n" + END_MARKER;

            // Remove existing block between markers
            originalSource = originalSource.replaceAll(
                    Pattern.quote(START_MARKER) + "[\\s\\S]*?" + Pattern.quote(END_MARKER),
                    autoGeneratedBlock
            );

            // If markers weren't present, inject before closing class brace
            if (!originalSource.contains(START_MARKER)) {
                originalSource = originalSource.replaceAll(
                        "(?=\\}\\s*$)",
                        "\n\n    " + autoGeneratedBlock.replaceAll("(?m)^", "    ") + "\n"
                );
            }

            Files.writeString(sourceFilePath, originalSource);
            System.out.println("Updated: " + configClass.getSimpleName());
        }
    }

    private static List<Class<?>> findAllConfigSubclasses() throws IOException {
        List<Class<?>> subclasses = new ArrayList<>();
        Path rootPath = Paths.get(SRC_DIR);
        Files.walk(rootPath)
                .filter(p -> p.toString().endsWith(".java"))
                .forEach(path -> {
                    try {
                        String className = toClassName(rootPath, path);
                        Class<?> clazz = Class.forName(className);
                        if (FragaliciousConfig.class.isAssignableFrom(clazz) && !clazz.equals(FragaliciousConfig.class)) {
                            subclasses.add(clazz);
                        }
                    } catch (Throwable ignored) {}
                });
        return subclasses;
    }

    private static Path findSourceFilePath(Class<?> clazz) {
        String relPath = clazz.getName().replace('.', '/') + ".java";
        Path fullPath = Paths.get(SRC_DIR, relPath);
        return Files.exists(fullPath) ? fullPath : null;
    }

    private static String toClassName(Path root, Path file) {
        Path relativePath = root.relativize(file);
        return relativePath.toString().replace(File.separator, ".").replace(".java", "");
    }

    private static String generateGettersForClass(Class<?> clazz) {
        StringBuilder builder = new StringBuilder();

        for (Field field : clazz.getDeclaredFields()) {
            if (!ConfigObject.class.isAssignableFrom(field.getType())) continue;

            String fieldName = field.getName();
            String methodName = "get" + capitalize(fieldName);
            String returnType = extractGenericType(field);

            builder.append("public ").append(returnType).append(" ").append(methodName).append("() {\n")
                    .append("    return this.").append(fieldName).append(".getValue();\n")
                    .append("}\n\n");
        }

        return builder.toString().trim();
    }

    private static String extractGenericType(Field field) {
        Class<?> fieldClass = field.getType();  // e.g. FloatConfigObject
        Type genericSuperclass = fieldClass.getGenericSuperclass();

        if (genericSuperclass instanceof ParameterizedType parameterizedType) {
            Type actualType = parameterizedType.getActualTypeArguments()[0];
            if (actualType instanceof Class<?> clazz) {
                return clazz.getSimpleName();  // e.g. Float
            } else {
                return actualType.getTypeName()
                        .replace("java.lang.", "")
                        .replace('$', '.');
            }
        }

        return "Object";
    }



    private static String capitalize(String name) {
        return Character.toUpperCase(name.charAt(0)) + name.substring(1);
    }
}
