package org.brassbrewery.fragaliciousCore.database;

import org.brassbrewery.fragaliciousCore.configs.FragaliciousConfig;
import org.brassbrewery.fragaliciousCore.configs.objects.BooleanConfigObject;
import org.brassbrewery.fragaliciousCore.configs.objects.IntegerConfigObject;
import org.brassbrewery.fragaliciousCore.configs.objects.StringConfigObject;
import org.brassbrewery.fragaliciousCore.structure.FragaliciousPlugin;

import java.nio.file.Path;

public class DatabaseConfig extends FragaliciousConfig {
    private BooleanConfigObject useMYSQL;
    private StringConfigObject jdbcUrl;
    private StringConfigObject username;
    private StringConfigObject password;
    private IntegerConfigObject poolSize;
    private IntegerConfigObject maxLifetime;
    private IntegerConfigObject connectionTimeout;
    private StringConfigObject tablePrefix;
    public DatabaseConfig(FragaliciousPlugin plugin, Path directoryPath, Path configPath) {
        super(plugin, directoryPath, configPath);
    }

    public DatabaseConfig(FragaliciousPlugin plugin, String configName) {
        super(plugin, configName);
    }

    @Override
    public void registerAllConfigObjects() {
        useMYSQL = new BooleanConfigObject("isSQL", false, "Set true to use MySQL/MariaDB set. Set false to use a SQLLite file");
        jdbcUrl = new StringConfigObject("mysql.jdbcURL", "jdbc:mysql://localhost:3306/mydatabase", "The JDBC URL");
        username = new StringConfigObject("mysql.username", "admin", "The username to database");
        password = new StringConfigObject("mysql.password", "SuperSecretP@ssword", "The password to your database. Please use safe and secure passwords");
        poolSize = new IntegerConfigObject("mysql.poolsize", 3, "The maximum number of connections allowed to the database. " +
                "\nDefault is 3");
        maxLifetime = new IntegerConfigObject("mysql.maxlifetime", 300000, "The maximum lifetime in milliseconds for an idle connection before it is closed." +
                "\n Default is 300000 (5 minutes)");
        connectionTimeout = new IntegerConfigObject("mysql.connectiontimeout", 10000, "The maximum amount of time in milliseconds that a client will wait for a connection from the pool. " +
                "\n Default is 10000 (10 seconds)");
        tablePrefix = new StringConfigObject("tableprefix", "fragalicious_", "The prefix you want to put in front of all tables created by this plugin.");
        registerConfigObject(useMYSQL);
        registerConfigObject(jdbcUrl);
        registerConfigObject(username);
        registerConfigObject(password);
        registerConfigObject(poolSize);
        registerConfigObject(maxLifetime);
        registerConfigObject(connectionTimeout);
        registerConfigObject(tablePrefix);
    }


        // <AUTO-GENERATED-GETTERS-START>
public Boolean getUseMYSQL() {
    return this.useMYSQL.getValue();
}

public String getJdbcUrl() {
    return this.jdbcUrl.getValue();
}

public String getUsername() {
    return this.username.getValue();
}

public String getPassword() {
    return this.password.getValue();
}

public Integer getPoolSize() {
    return this.poolSize.getValue();
}

public Integer getMaxLifetime() {
    return this.maxLifetime.getValue();
}

public Integer getConnectionTimeout() {
    return this.connectionTimeout.getValue();
}

public String getTablePrefix() {
    return this.tablePrefix.getValue();
}
// <AUTO-GENERATED-GETTERS-END>
}
