plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"
}

dependencies {

    testImplementation 'org.mockbukkit.mockbukkit:mockbukkit-v1.21:4.49.0'
    implementation("org.spongepowered:configurate-core:4.2.0")
    implementation("org.spongepowered:configurate-hocon:4.2.0")
    implementation ('com.zaxxer:HikariCP:6.3.0')
    compileOnly "net.milkbowl.vault:VaultUnlockedAPI:2.11"
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
tasks.register('generateConfigGetters', JavaExec) {
    group = 'utility'
    description = 'Generates getters for FragaliciousConfig fields'
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('org.brassbrewery.fragaliciouscore.configs.GenerateFragaliciousGetters')
}
tasks {
    runServer {
        minecraftVersion("1.21")
    }
}
test {
    useJUnitPlatform()
}
java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

